version: '3'
services:
  muon-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - TOKEN=${TOKEN}
    volumes:
      - ./main:/app/bot
    command: python bot/main.py